/** Catálogo de rubros para búsqueda de leads: negocios locales que existen en
 * Google Maps y que típicamente atienden todo a mano (sin sistema de turnos ni
 * WhatsApp automatizado). Los textos son los términos de búsqueda reales que se
 * mandan al scraper - por eso van en singular y como la gente busca en Maps
 * (español rioplatense). */

export interface CategoriaNichos {
  categoria: string
  nichos: string[]
}

export const CATALOGO_NICHOS: CategoriaNichos[] = [
  {
    categoria: "Salud",
    nichos: [
      "consultorio odontológico",
      "kinesiología",
      "consultorio de psicología",
      "nutricionista",
      "consultorio médico",
      "centro de estética",
      "depilación láser",
      "laboratorio de análisis clínicos",
      "fonoaudiología",
      "acupuntura",
      "podología",
      "óptica",
      "farmacia",
      "residencia para adultos mayores",
      "vacunatorio",
      "quiropraxia",
    ],
  },
  {
    categoria: "Belleza y estética",
    nichos: [
      "peluquería",
      "barbería",
      "diseño de cejas",
      "extensión de pestañas",
      "manicura",
      "nail art",
      "maquillaje profesional",
      "centro de depilación",
      "bronceado artificial",
      "estudio de tatuajes",
      "piercing",
      "spa",
      "masajes y terapias",
    ],
  },
  {
    categoria: "Gastronomía",
    nichos: [
      "restaurante",
      "pizzería",
      "hamburguesería",
      "cafetería",
      "pastelería",
      "casa de tortas",
      "panadería",
      "heladería",
      "parrilla",
      "restaurante japonés",
      "rotisería",
      "empanadas",
      "casa de jugos",
      "dietética",
      "vinoteca",
      "distribuidora de bebidas",
    ],
  },
  {
    categoria: "Fitness y bienestar",
    nichos: [
      "gimnasio",
      "estudio de pilates",
      "box de crossfit",
      "estudio de yoga",
      "personal trainer",
      "escuela de natación",
      "estudio de danza",
      "academia de artes marciales",
      "cancha de pádel",
      "entrenamiento funcional",
    ],
  },
  {
    categoria: "Servicios profesionales",
    nichos: [
      "estudio jurídico",
      "estudio contable",
      "inmobiliaria",
      "corredor de propiedades",
      "productor de seguros",
      "estudio de arquitectura",
      "estudio de ingeniería",
      "asesoría financiera",
      "gestoría",
      "asesor de inversiones",
      "empresa de topografía",
      "tasador de propiedades",
      "traductor público",
    ],
  },
  {
    categoria: "Hogar y refacción",
    nichos: [
      "carpintería",
      "marmolería",
      "vidriería",
      "herrería",
      "electricista",
      "destapaciones",
      "pintura de obra",
      "durlock",
      "paisajismo",
      "jardinería",
      "control de plagas",
      "instalación de aire acondicionado",
      "energía solar",
      "muebles a medida",
      "aberturas de aluminio",
      "constructora",
      "empresa de albañilería",
      "piletas",
      "impermeabilización",
      "canaletas y techos",
      "portones automáticos",
      "seguridad electrónica",
      "cerrajería",
      "decoración de interiores",
    ],
  },
  {
    categoria: "Automotor",
    nichos: [
      "taller mecánico",
      "electricidad del automóvil",
      "chapa y pintura",
      "detailing automotor",
      "lavadero de autos",
      "gomería",
      "casa de repuestos",
      "sonido para autos",
      "polarizado de vidrios",
      "parabrisas",
      "gestoría del automotor",
      "autoescuela",
      "alquiler de autos",
      "auxilio y grúa",
      "repuestos y taller de motos",
    ],
  },
  {
    categoria: "Mascotas",
    nichos: [
      "pet shop",
      "peluquería canina",
      "veterinaria",
      "hotel para perros",
      "adiestrador canino",
      "guardería canina",
    ],
  },
  {
    categoria: "Educación",
    nichos: [
      "instituto de idiomas",
      "jardín de infantes",
      "apoyo escolar",
      "escuela de música",
      "clases de guitarra",
      "escuela de computación",
      "curso de oficios",
      "escuela de gastronomía",
      "clases de canto",
      "robótica para chicos",
    ],
  },
  {
    categoria: "Comercio local",
    nichos: [
      "local de ropa",
      "boutique",
      "zapatería",
      "joyería",
      "relojería",
      "mueblería",
      "colchonería",
      "librería",
      "florería",
      "regalería",
      "perfumería",
      "cosmética",
      "mercería",
      "juguetería",
      "corralón",
      "pinturería",
      "casa de iluminación",
      "dietética",
      "kiosco",
    ],
  },
  {
    categoria: "Eventos y fiestas",
    nichos: [
      "servicio de catering",
      "salón de eventos",
      "fotógrafo",
      "productora de video",
      "ambientación de fiestas",
      "alquiler de juegos para fiestas",
      "organización de eventos",
      "mesa dulce",
      "alquiler de mesas y sillas",
      "DJ para fiestas",
      "banda para eventos",
    ],
  },
  {
    categoria: "Turismo y hospedaje",
    nichos: [
      "posada",
      "hotel",
      "hostel",
      "agencia de turismo",
      "alquiler temporario",
      "quinta para eventos",
    ],
  },
  {
    categoria: "Tecnología y reparaciones",
    nichos: [
      "servicio técnico de celulares",
      "servicio técnico de computadoras",
      "servicio técnico de electrodomésticos",
      "imprenta",
      "cartelería y gigantografía",
      "casa de computación",
      "reparación de consolas",
      "instalación de cámaras de seguridad",
    ],
  },
  {
    categoria: "Otros servicios",
    nichos: [
      "lavadero de ropa",
      "taller de costura",
      "compostura de calzado",
      "empresa de mudanzas",
      "transporte de cargas",
      "coworking",
      "lavado de tapizados",
      "organización de placares",
      "cuidado de adultos mayores",
      "empresa de limpieza",
    ],
  },
]

/** Limite espelhado do backend (MAX_NICHOS_BUSCA_MAPA). */
export const LIMITE_NICHOS_POR_BUSCA = 15

// faixa dos acentos combinantes do Unicode (NFD separa "é" em "e" + acento)
const REGEX_ACENTOS_COMBINANTES = /[̀-ͯ]/g

export function normalizarParaBusca(texto: string): string {
  return texto.normalize("NFD").replace(REGEX_ACENTOS_COMBINANTES, "").toLowerCase()
}
